### ISSUE TITLE
queue never drains

### ISSUE THREAD

**Issue by markbrown4** [bradoyler/route-cache#25] opened 2017-02-22 17:56 UTC
Hello 👋, me again.

If the first request to come into cacheSeconds fails to call `send`, `json` or `redirect` for whatever reasons it starts a queue that will never resolve.  Any request to come in after this point gets pushed to the queue and the requests will time out.  We saw this crop up when an unexpected client error (406) triggered an error in our code.

The fix is to move draining of the queue out of `rawSend` into here when the response 'finish' event fires.  This event fires for successful requests and the the errors that I mentioned above.

```js
// first request will get rendered output
if (queues[key].length === 0) {
  res.on('finish', function(data) {
    var subscriber = null
    while (queues[key].length > 0) {
      subscriber = queues[key].shift()
      process.nextTick(subscriber)
    }
    delete queues[key]
  })
}
```

Because the first request was unable to get a response and create an item in the cache, you also need to decide what to do with the requests in the queue.  Perhaps ending them or raising an error that will reach the express error handler.

```js
queues[key].push(function () {
  var value = cacheStore.get(key)
  if (!value) {
    res.end()
  } else if (value.isJson) {
    res.json(value.body)
  } else {
    res.send(value.body)
  }
})
```

**Comment by bradoyler** [comment] 2017-02-23 01:35
👍

**Comment by markbrown4** [comment] 2017-02-23 15:20
`res.on('finish')` isn't a silver bullet, it needs more thought.

If you wanted to replicate the issue you can put a bug in the error handler like this:

```js
app.use(function(err, req, res, next) {
  res.format({
    html: function() {
      res.send('Error')
    },
    json: function() {
      res.json({
        statusCode: err.statusCode
      })
    }
  })
}
```

Then make a request with an "Accept: foobar" header, res.format will throw an error and you'll see an item in the queue.  The route will now never respond even if you removing the dodgy header.

Not sure if there's a way to catch this error and empty the queue..

**Comment by bradoyler** [comment] 2017-08-26 07:00
closing as I'm not able to reproduce

**Closed by bradoyler** 2017-08-26 07:00 UTC

**Comment by bradoyler** [comment] 2017-08-27 18:02
This fix should address this issue: https://github.com/bradoyler/route-cache/commit/10f69a086f31
